import applications_linear_algebraic_groups_sciences_foundation_canonical_lane_mathlib.GateLemmas
namespace HautevilleHouse
namespace applications_linear_algebraic_groups_sciences_foundation_canonical_lane_mathlib
structure ConstrainedTheoremClosure where
  admissible :: intro :: constraint :: consequence :: proof ::
theorem canonical : ConstrainedTheoremClosure :=
  ConstrainedTheoremClosure.intro
end applications_linear_algebraic_groups_sciences_foundation_canonical_lane_mathlib
end HautevilleHouse
